#!/usr/bin/env python3
#
# cvgen v0.4 2021-06-27

# Import modules

import argparse
import cvdata as cv
import geometry as geo
import functions as fn
import output as out
import os

# Version
version_num = '0.4'
version_dat = '2021-06-27'
version_str = '{} ({})'.format(version_num, version_dat)

def main():
    # Define argument parsers and subparsers
    parser = argparse.ArgumentParser(description='A program for generating CVs in LaTeX. Written by Johannes Engelmayer')

    parser.add_argument('-V', '--version', action='version', version='%(prog)s '+ version_str)
    parser.add_argument('-v', '--verbose', action='count', default=0,
                        help='verbosity level (-v, -vv, -vvv): '
                        'default = single-line output, v = multi-line, vv = detailed, vvv = array output')
    parser.add_argument('-q', '--quiet', action='store_true',
                        help=('disable terminal output (terminates all verbosity)'))
    parser.add_argument('-l', '--latex', action='store_true',
                        help='execute pdflatex after creating *.tex file')
    parser.add_argument('-s', '--show', action='store_true',
                        help='show pdf after executing pdflatex (implies -l)')
    parser.add_argument('outfile', nargs='?', help='write to file')

    args = parser.parse_args()

    # Check verbosity level

    verbosity = args.verbose
    if args.quiet is True:
        verbosity = -1
    if verbosity >= 1:
        print(args)


    # Use config directory or create one

    config_dir = os.path.expanduser('~/.config/cvgen')
    fn.check_config_dir(config_dir)
    config_file_data = os.path.join(config_dir, 'cvdata.json')
    config_file_geo = os.path.join(config_dir, 'cvgeometry.json')
    fn.check_config_file(config_file_data)
    fn.check_config_file(config_file_geo)

    config_data = fn.read_config(config_file_data)
    config_geo = fn.read_config(config_file_geo)
    person = cv.split_config(config_data)[0]
    color_background = 'Blues-G'
    layout = geo.split_config(config_geo)[0]
    skill_decoration = True
    # Skill layout
    skill_circle = geo.split_config(config_geo)[5]
    skill_layout = geo.split_config(config_geo)[6]
    # Skill items
    skill1 = cv.SkillItem(name='Python', level=4)
    skill2 = cv.SkillItem(name='Bash', level=3)
    skill3 = cv.SkillItem(name='LaTeX', level=5)
    skill4 = cv.SkillItem(name='Git', level=5)
    # Skill groups
    group1 = cv.SkillGroup(name='Programming', skill_items=[skill1, skill2, skill3])
    group2 = cv.SkillGroup(name='Software/Tools', skill_items=[skill4])
    skills = []
    for i in range(skill_layout.number):
        skills.append('\\filldraw[color={}] ({}, {}) circle [radius={}mm]'.format(skill_circle.fillcolor, 2+i*skill_layout.distance/10, 5, skill_circle.radius))
    print(skills)

    # Check file extension
    outfile = str(args.outfile)
    if outfile[-4:0] != '.tex':
        outfile = outfile + '.tex'
    outfile = os.path.abspath(outfile)
    # Write to file
    with open(outfile, 'w', encoding='UTF-8') as f:
        # Write comment with program and version info 
        f.write('% ===== LaTeX code generated by cvgen v{} =====\n'.format(version_str))
        # Write LaTeX preamble
        for line in out.preamble():
            f.write(line + '\n')
        f.write(r'\begin{document}' + '\n')
        # Write definitions of variables
        f.write('\t' + r'\tikzmath{' + '\n')
        for line in out.declare_variables(layout, config_geo):
            f.write('\t\t' + line + '\n')
        f.write('\t' + r'}' + '\n')
        # Write layer declaration
        for line in out.declare_layers():
            f.write('\t' + line + '\n')
        f.write('\t' + r'\begin{tikzpicture}' + '\n')
        for line in out.draw_background(layout, config_geo):
            f.write(line + '\n')
        if skill_decoration is True:
            f.write('\t\t' + r'\begin{pgfonlayer}{foreground}' + '\n')
            for i in range(skill_layout.number):
                f.write('\t\t\t'+ skills[i] + ';\n')
            f.write('\t\t' + r'\end{pgfonlayer}' + '\n')
        f.write('\t' + r'\end{tikzpicture}' + '\n')
        f.write(r'\end{document}' + '\n')
    if verbosity >=1:
        print('[output] LaTeX file {} created.'.format(outfile))
    if (args.latex or args.show) is True:
        output_dir = os.path.dirname(outfile)
        cmd = 'pdflatex -synctex=1 -interaction=nonstopmode -output-directory {} {}'.format(output_dir, outfile)
        if verbosity >=1:
            print('[output] Executing pdfLaTeX: {} ...'.format(cmd))
        os.system(cmd)
        if verbosity >=1:
            print('[output] ... done!')
    if args.show is True:
        outfile_pdf = outfile[0:-4] + '.pdf'
        if verbosity >=1:
            print('[output] Opening PDF file via: mupdf {} ...'.format(outfile_pdf))
        os.system('mupdf {}'.format(outfile_pdf))


if __name__ == '__main__':
    main()

